export const STORAGE_KEYS = {
  theme: 'suh_theme',
  resumeDraft: 'suh_resume_draft_v1',
  pomodoroHistory: 'suh_pomodoro_history_v1',
}

export const TOOLS = [
  {
    id: 'resume-builder',
    name: 'Resume Builder',
    description: 'Create a polished resume with live preview, templates, and PDF export.',
    path: '/tools/resume-builder',
    tag: 'Resume',
    featured: true,
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images client-side using Canvas. No uploads.',
    path: '/tools/image-compressor',
    tag: 'Image',
    featured: true,
  },
  {
    id: 'image-converter',
    name: 'Image Converter',
    description: 'Convert between JPG, PNG, and WebP in the browser.',
    path: '/tools/image-converter',
    tag: 'Image',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images with optional aspect ratio lock.',
    path: '/tools/image-resizer',
    tag: 'Image',
  },
  {
    id: 'images-to-pdf',
    name: 'Images → PDF',
    description: 'Combine multiple images into a single PDF.',
    path: '/tools/images-to-pdf',
    tag: 'Image',
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Best-effort client-side PDF size reduction and re-save.',
    path: '/tools/pdf-compressor',
    tag: 'PDF',
    featured: true,
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Merge multiple PDFs, reorder them, and download.',
    path: '/tools/pdf-merger',
    tag: 'PDF',
  },
  {
    id: 'notes-to-pdf',
    name: 'Notes → PDF',
    description: 'Write notes with headings and export to PDF.',
    path: '/tools/notes-to-pdf',
    tag: 'Study',
    featured: true,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF → Images',
    description: 'Convert PDF pages to PNG images in the browser.',
    path: '/tools/pdf-to-images',
    tag: 'Document',
    featured: true,
  },
  {
    id: 'docx-to-pdf',
    name: 'DOCX → PDF',
    description: 'Render DOCX client-side and export to PDF (no server storage).',
    path: '/tools/docx-to-pdf',
    tag: 'Document',
  },
  {
    id: 'cgpa-calculator',
    name: 'CGPA Calculator',
    description: 'Compute GPA/CGPA from subjects, credits, and grades.',
    path: '/tools/cgpa-calculator',
    tag: 'Study',
  },
  {
    id: 'pomodoro-timer',
    name: 'Pomodoro Timer',
    description: '25/5 timer with session history saved locally.',
    path: '/tools/pomodoro-timer',
    tag: 'Study',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong passwords with controls.',
    path: '/tools/password-generator',
    tag: 'Other',
  },
  {
    id: 'video-summary',
    name: 'Video Summary',
    description: 'Extract video metadata + write a summary + export as TXT/PDF.',
    path: '/tools/video-summary',
    tag: 'Video',
    featured: true,
  },
  {
    id: 'video-to-audio',
    name: 'Video → Audio',
    description: 'Extract audio in-browser (WAV fast, MP3 optional via ffmpeg).',
    path: '/tools/video-to-audio',
    tag: 'Video',
  },
  {
    id: 'youtube-summary',
    name: 'YouTube Summary',
    description: 'Paste a YouTube link, fetch metadata, write a manual summary, export TXT/PDF.',
    path: '/tools/youtube-summary',
    tag: 'Video',
  },
]
